apiVersion: v1
kind: Service
metadata:
  name: student-app
spec:
  type: {{ .Values.serviceType.app }}
  selector:
    app: student-app
  ports:
  - port: {{ .Values.app.containerPort }}
    targetPort: {{ .Values.app.containerPort }}
