apiVersion: v1
kind: Service
metadata:
  name: student-db
spec:
  type: {{ .Values.serviceType.db }}
  selector:
    app: student-db
  ports:
  - port: {{ .Values.db.port }}
    targetPort: {{ .Values.db.port }}
